# Generated by Django 5.1.3 on 2024-12-12 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_role_alter_user_table_alter_user_role'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='user',
            table=None,
        ),
    ]
