# Generated by Django 5.1.3 on 2024-11-24 17:25

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cows', '0001_initial'),
        ('members', '0002_remove_user_cow_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('phone', models.CharField(blank=True, max_length=12, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cow_id', models.OneToOneField(blank=True, default=uuid.uuid4, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='report_cow', to='cows.cow')),
                ('user_id', models.OneToOneField(blank=True, default=uuid.uuid4, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='report_user', to='members.user')),
            ],
        ),
    ]
