# Generated by Django 5.1.3 on 2024-11-24 17:30

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=15)),
                ('names', models.CharField(max_length=40)),
                ('message', models.CharField(max_length=20)),
                ('created_at', models.CharField(max_length=30)),
            ],
        ),
    ]
